runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: robots\.txt
- url: /googleb37aaf4171d54954\.html
  static_files: static/googleb37aaf4171d54954.html
  upload: googleb37aaf4171d54954\.html
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  secure: always

libraries:
- name: ssl
  version: latest